#Master App Server
master:
  fileIn: "Desktop/files/input"
  fileProcessed: "Desktop/files/processed"
  fileWrite: "Desktop/files/output"
  pollFrequency: "1000"

#Partner 1 Database
#Dev will use in-memory Derby Database
partner1:
  name: "Food and Savings"
  queue: "foodnsavings"
  db:
    url: "jdbc:derby:memory:training"
    driver: "org.apache.derby.jdbc.EmbeddedDriver"

#Partner 2 FTP Credentials. 
#Dev will use in-memory FTP server using MockFtpServer Java package. Change the port number here if your local machine is currently using port 9178
partner2:
  name: "Meals n Go"
  queue: "mealsngo"
  ftp:
    host: "localhost"
    port: "9178"
    username: "user"
    password: "password"
    root: "/data/"
    
#Partner 3 File Server
partner3:
  name: "Online Retail Plus"
  queue: "oretailplus"
  fileWrite: "Desktop/partner3/receive"