#%RAML 1.0 NamedExample
value:
  ID : 1
  firstName : "Ben"
  lastName : "Jensen"
  address : "1234 W 5th Street"
  postal : "75481"
  country : "USA"
  miles : 123
  creationDate? : 2016-02-28T16:41:41.090Z
  type : "business"
