#%RAML 1.0 NamedExample
value:
  -
    
    firstName : "Ben"
    lastName : "Jensen"
    address : "1234 W 5th Street"
    postal : "75481"
    country : "USA"
    miles : 123
    type : "business"
  -
    
    firstName : "John"
    lastName : "Doe"
    address : "1738 N 13th Street"
    postal : "60616"
    country : "USA"
    miles : 456
    type : "personal"

